\documentclass[12pt,]{article}
\usepackage[superscript,nomove]{cite} % use if \cite is used and superscripts wanted
\usepackage[utf8]{inputenc}
\usepackage[a4paper, margin=1.2in]{geometry}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{lscape}
\usepackage{bbm}
\usepackage{mathrsfs}
\usepackage{amssymb}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{listings}
\usepackage{color} %red, green, blue, yellow, cyan, magenta, black, white
\usepackage{longtable}
\usepackage{tabularx}
\usepackage{rotating}
\usepackage{fancyhdr}          % this and next line are for fancy headers/footers
\pagestyle{fancy}
\usepackage{float}

\usepackage{Sweavel}
\SweaveOpts{keep.source=TRUE}
% To produce both postscript and pdf graphics, remove the eps and pdf
% parameters in the next line.  Set default plot size to 6x4 in.
\SweaveOpts{eps = FALSE, pdf = TRUE}
%\SweaveOpts{width=8, height=6}



\begin{document}
\begin{titlepage}
\begin{center}

\vspace*{5em}
{\huge Relative Efficiency of Pennsylvania Dairy Farms\\[0.4cm] }
\color{blue}\hrule
\color{black}
\vspace{100mm}
\noindent
\Large 
Robert D \textsc{Weaver}\\
and\\
Jiachuan \textsc{Tian}

\today
\vfill
\end{center}
\end{titlepage}



%--------------------------------
\section{Data Desciption}
%--------------------------------
In this note, we present an analysis of farms' production efficiencies using the DEA approach. The data we use is monthly data of a small set of Pennsylvania dairy farms. The data was collected from 53 farms that participated in the study. The three datasets can be summarized as:

<<warning= F, message=FALSE, echo=FALSE>>=
library(xlsx)
library(dplyr)
library(magrittr)
library(Benchmarking)
library(ggplot2)
library(knitr)
library(xtable)
library(tidyr)
library(censReg)
@

<<read data, echo = F>>=
data = read.xlsx(file = 'Monthly.xlsx', 1, stringsAsFactors = FALSE)
data$MUN = - data$MUN
data$Fecal_Starch = - data$Fecal_Starch
data_year = read.xlsx(file = "Annual.xlsx", 3)
data_year$Farm_ID = factor(data_year$Farm_ID)
data = merge(data, data_year, by = c("Farm_ID", "year"), all.x = T)
data = dplyr::tbl_df(data)
Monthly_data =
  data%>%
  dplyr::distinct() %>%
  group_by(Farm_ID) %>%
  arrange(DHIDate)

Test_data = 
  Monthly_data %>%
  dplyr::filter(!is.na(Sample_Number) &
                !is.na(MUN)&
                !is.na(pH)  )%>%
  group_by(Farm_ID)


Annual_data = 
  Test_data %>%
  dplyr::filter(!is.na(Pur_Feed_Calc) &
                !is.na(Feed_Cost__All_Animals__Annual) &
                !is.na(Corn_silage))%>%
  group_by(Farm_ID)


Number_Obs_data = data.frame(matrix(lapply(list(Monthly_data, Test_data, Annual_data), function(x)dim(x)[1]), ncol = 1))
Number_Obs_data = cbind(Number_Obs_data, c("Monthly Data", "Test Data", "Annual Data"),
                        c("IOFC data collected for each month 2013-2015, 53 farms, test date data included",
                             "Test dates pooled such that for each farm there are 3-5 obs on different test dates",
                             "2013-2015 although 53 farms x 2yrs => 106 obs, many farms had missing data"))
colnames(Number_Obs_data) = c("Number_obs", "Data_set", "Comments")
Number_Obs_data = Number_Obs_data[,c(2,1,3)]
@

<<echo = False, results=tex>>=
mis_tab = xtable(Number_Obs_data,
                 caption ="Summary of Datasets", 
                 label = "Table-1")
align(mis_tab) = "ll|l|X"
print(mis_tab, tabular.environment = "tabularx", width = "\\linewidth")
@


%--------------------------------
\section{Models}
%--------------------------------
Now we define the input and output variables we use in the models. The inputs variates we choose are:
\begin{center}
Number of Cows, Dry Matter, CP, Starch DM, pH\\
Purchased Feed, Feed Cost, Corn silage\\
\end{center}
Note inputs in last row below are only in annual data.

The outputs variates we choose are:
\begin{center}
Milk per Milk Cow, Fat, Protein, (negative) MUN, (negative)Fecal Starch
\end{center}

<<echo = F>>=
Inputs = c("X__Cows",
           "Dry_Matter", "CP__" , "Starch___DM", "pH", 
           "Pur_Feed_Calc", "Feed_Cost__All_Animals__Annual", "Corn_silage")

Outputs = c("Milk_per_Milk_Cow", "X__Fat", "X__Pro",
            "MUN", "Fecal_Starch")
@


\subsection{Model 4-1 Test Data}
Recall in test data, the test dates are pooled such that for each farm there are 3-5 obs on different test dates. For each of the output variables, we conduct DEA for all farms. The average efficiency scores can be summarized in table 2.

<<echo = False, results = tex>>=
Inputs_Model4 = Inputs[1:5]
eff_Model41 = data.frame(matrix(NA, ncol = 6, nrow = dim(Test_data)[1]))
colnames(eff_Model41) = c("Farm_ID", Outputs)
eff_Model41$Farm_ID = Test_data$Farm_ID

for(a in Outputs){
  dea_local = dea(data.frame(Test_data[Inputs_Model4]), data.frame(Test_data[a]))
  eff_Model41[a] = dea_local$eff
}
eff_Model41_ = eff_Model41

eff_Model41 %<>%
  group_by(Farm_ID)%>%
  summarise_each(., funs(mean))

mis_tab1 = xtable(eff_Model41,
                 caption ="Average Test Data Efficiency Score by Farm", 
                 label = "Table-2")
align(mis_tab1) = "l|l|l|l|l|l|l"
print(mis_tab1, tabular.environment = "longtable", width = "\\linewidth")
@
Each column is table 2 reports the average efficiency score based on that column as output. We plot the distribution of the efficiency scores in figure 1 and figure 2.

\begin{figure}[H]
<<11, fig=TRUE, height= 5, width= 7, warning= F, message=FALSE, echo=FALSE>>=
eff_Model41_vec = data.frame(eff = numeric(),
                             output = character())
for (a in Outputs) {
  local_df = data.frame(eff_Model41[a])
  colnames(local_df) = "eff"
  local_df$output = a
  local_df = local_df[,c(2,1)]
  eff_Model41_vec = rbind(eff_Model41_vec, local_df)
}


ggplot(eff_Model41_vec, aes(eff)) +
  geom_histogram(alpha = 0.8, aes(y = ..density..), position = 'stack')+
  facet_grid(.~output)+
  xlab("Production Efficiency")+
  ylab("Number of Farms")+
  ggtitle("Histogram of Production Efficiency by Output")+
  scale_fill_manual(name='Output', values=c("#0066FF", "#0033CC", "#33FFFF", "#99CC00", "#FFCC66", "#FF9933", "#FF99FF", "#9933FF","#FF0000"))


@
\caption{Histogram of Average Efficiency Score for each farm}
\end{figure}


\begin{figure}[H]
<<22, fig=TRUE, height= 5, width= 7, warning= F, message=FALSE, echo=FALSE>>=
ggplot(eff_Model41_vec, aes(eff, fill = output)) + geom_density(alpha = 0.2)
@
\caption{Distribution of Average Efficiency Score for each farm}
\end{figure}

\subsection{Model 4-2 Test Data Seperated}
In the section, we examine whether the efficiency of farms vary over time.  Thus we partition the test data based on test date. Each test date considered a different sample.

The efficiency scores are reported in table 3.
<<echo = False, results = tex>>=
eff_Model42 = data.frame(matrix(NA, ncol = 7, nrow = dim(Test_data)[1]))
colnames(eff_Model42) = c("Farm_ID", "Season_Year", Outputs)
eff_Model42$Farm_ID = Test_data$Farm_ID
eff_Model42$Season_Year = factor(Test_data$Season_Year, c("Fall 2013", "Spring 2014", "Fall 2014", "Spring 2015", "Fall 2015"))


for (a in Outputs){
  for (t in unique(Test_data$Season_Year)){
    local_data = Test_data[Test_data$Season_Year == t,]
    local_eff = dea(data.frame(local_data[Inputs_Model4]), data.frame(local_data[a]))$eff
    eff_Model42[Test_data$Season_Year == t, a] = local_eff
    }
  }

mis_tab2 = xtable(eff_Model42,
                 caption ="Test Data Efficiency Score over Time", 
                 label = "Table-3")
align(mis_tab2) = "l|l|l|l|l|l|l|l"
print(mis_tab2, tabular.environment = "longtable", width = "\\linewidth")
@


We plot these in the following figures:
\begin{figure}[H]
<<fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
a = Outputs[1]
ggplot(eff_Model42, aes(x = Season_Year, y = eff_Model42[,a], group = factor(Farm_ID), color = factor(Farm_ID)))+
      #geom_line()+
      geom_point()+
      xlab("Season/Year")+
      ylab("Production Efficiency")+
      ggtitle(paste('Histogram of Efficiency Scores of', a))+
      labs(color = "Farm ID")
  
@
\caption{Test Data Efficiency Score over Time (output: Milk)}
\end{figure}

\begin{figure}[H]
<<fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
a = Outputs[2]
ggplot(eff_Model42, aes(x = Season_Year, y = eff_Model42[,a], group = factor(Farm_ID), color = factor(Farm_ID)))+
      #geom_line()+
      geom_point()+
      xlab("Season/Year")+
      ylab("Production Efficiency")+
      ggtitle(paste('Histogram of Efficiency Scores of', a))+
      labs(color = "Farm ID")
@
\caption{Test Data Efficiency Score over Time (output: Fat)}
\end{figure}
\begin{figure}[H]
<<fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
a = Outputs[3]
ggplot(eff_Model42, aes(x = Season_Year, y = eff_Model42[,a], group = factor(Farm_ID), color = factor(Farm_ID)))+
      #geom_line()+
      geom_point()+
      xlab("Season/Year")+
      ylab("Production Efficiency")+
      ggtitle(paste('Histogram of Efficiency Scores of', a))+
      labs(color = "Farm ID")
@
\caption{Test Data Efficiency Score over Time (output: Protein)}
\end{figure}
\begin{figure}[H]
<<fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
a = Outputs[4]
ggplot(eff_Model42, aes(x = Season_Year, y = eff_Model42[,a], group = factor(Farm_ID), color = factor(Farm_ID)))+
      #geom_line()+
      geom_point()+
      xlab("Season/Year")+
      ylab("Production Efficiency")+
      ggtitle(paste('Histogram of Efficiency Scores of', a))+
      labs(color = "Farm ID")
@
\caption{Test Data Efficiency Score over Time (output: MUN)}
\end{figure}
\begin{figure}[H]
<<fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
a = Outputs[5]
ggplot(eff_Model42, aes(x = Season_Year, y = eff_Model42[,a], group = factor(Farm_ID), color = factor(Farm_ID)))+
      #geom_line()+
      geom_point()+
      xlab("Season/Year")+
      ylab("Production Efficiency")+
      ggtitle(paste('Histogram of Efficiency Scores of', a))+
      labs(color = "Farm ID")
@
\caption{Test Data Efficiency Score over Time (output: Fecal Starch)}
\end{figure}

\subsection{Model 5 Annual Data}
In this section, we merge annual data into pooled test date data. We have 55 avaible observations in total. With annual data, we are able to use Purchased Feed, Feed Cost, Corn silage as input variables. For each of these output variables, we conduct DEA for all farms. The average efficiency scores can be summarized in table 4.

<<echo = False, results = tex>>=
eff_Model51 = data.frame(matrix(NA, ncol = 6, nrow = dim(Annual_data)[1]))
colnames(eff_Model51) = c("Farm_ID", Outputs)
eff_Model51$Farm_ID = Annual_data$Farm_ID

for(a in Outputs){
  dea_local = dea(data.frame(Annual_data[Inputs]), data.frame(Annual_data[a]))
  eff_Model51[a] = dea_local$eff
}

eff_Model51 %<>%
  group_by(Farm_ID)%>%
  summarise_each(., funs(mean))

mis_tab1 = xtable(eff_Model51,
                 caption ="Average Annual Data Efficiency Score by Farm", 
                 label = "Table-4")
align(mis_tab1) = "l|l|l|l|l|l|l"
print(mis_tab1, tabular.environment = "longtable", width = "\\linewidth")
@
Each column is table 4 reports the average efficiency score based on that column as output. We plot the distribution of the efficiency scores in figure 8 and figure 9.

\begin{figure}[H]
<<33, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
eff_Model51_vec = data.frame(eff = numeric(),
                             output = character())
for (a in Outputs) {
  local_df = data.frame(eff_Model51[a])
  colnames(local_df) = "eff"
  local_df$output = a
  local_df = local_df[,c(2,1)] 
  eff_Model51_vec = rbind(eff_Model51_vec, local_df)
}
#ggplot(eff_Model51_vec, aes(eff, fill = output)) + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')


ggplot(eff_Model51_vec, aes(eff)) + 
  geom_histogram(alpha = 0.8, aes(y = ..density..), position = 'stack')+
  facet_grid(.~output)+
  xlab("Production Efficiency")+
  ylab("Number of Farms")+
  ggtitle("Histogram of Average Production Efficiency by Output")+
  scale_fill_manual(name='Output', values=c("#0066FF", "#0033CC", "#33FFFF", "#99CC00", "#FFCC66", "#FF9933", "#FF99FF", "#9933FF","#FF0000"))
@
\caption{Histogram of Average Efficiency Score for each farm}
\end{figure}


\begin{figure}[H]
<<44, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
ggplot(eff_Model51_vec, aes(eff, fill = output)) + geom_density(alpha = 0.2)
@
\caption{Distribution of Average Efficiency Score for each farm}
\end{figure}

\section{New Addition 03/31/2016}
\subsection{Plot efficiency versus Variates}
In this section we plot the efficiency score we got in section 2.1 (Model 4-1) versus fecal starch, starch digestibility, and MUN.

\begin{figure}[H]
<<03312016_1, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=
eff_Model41_plot = 
  eff_Model41_%>%
  select(., Farm_ID, Milk_per_Milk_Cow)%>%
  bind_cols(.,Test_data[c("Fecal_Starch", "Starch_Digestibility", "MUN")])
  

eff_Model41_plot%<>%
  gather(Variable_type, Variable, Fecal_Starch : MUN)

ggplot(eff_Model41_plot, aes(x = Variable, y = Milk_per_Milk_Cow))+
  geom_point(color = "#FF0000")+
  guides(colour=FALSE)+
  facet_grid(.~Variable_type, scale = "free_x")+
  xlab("Variates Value")+
  ylab("Production (Milk per Milk Cow) Efficiency")+
  ggtitle("Production (Milk per Milk Cow) Efficiency Score versus Variates")
@
\caption{Production (Milk per Milk Cow) Efficiency Score versus Variates}
\end{figure}

\begin{figure}[H]
<<03312016_2, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=

eff_Model42_plot = 
  eff_Model41_%>%
  select(., Farm_ID, Fecal_Starch)%>%
  bind_cols(.,Test_data[c("Fecal_Starch", "Starch_Digestibility", "MUN")])

colnames(eff_Model42_plot)[3] =  "Fecal_Starch_"

eff_Model42_plot%<>%
  gather(Variable_type, Variable, Fecal_Starch_: MUN)

ggplot(eff_Model42_plot, aes(x = Variable, y = Fecal_Starch))+
  geom_point(color = "#FF9933")+
  guides(colour=FALSE)+
  facet_grid(.~Variable_type, scale = "free_x")+
  xlab("Variates Value")+
  ylab("Production (Fecal Starch) Efficiency")+
  ggtitle("Production (Fecal Starch) Efficiency Scores versus Variates")
@
\caption{Production (Fecal Starch) Efficiency Scores versus Variates}
\end{figure}



\subsection{Plot efficiency versus Variates by Group (0-100 cows, 100-275 cows)}

\begin{figure}[H]
<<03312016_3, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=

FarmID_0_100 = 
Test_data %>%
  group_by(Farm_ID)%>%
  summarise_each(., funs(mean))%>%
  filter(X__Cows <= 100)%>%
  select(Farm_ID)

FarmID_100_275 = 
Test_data %>%
  group_by(Farm_ID)%>%
  summarise_each(., funs(mean))%>%
  filter(X__Cows <= 275 & X__Cows > 100)%>%
  select(Farm_ID)

eff_Model41_0_100_plot = 
eff_Model41_plot%>%
  filter(Farm_ID %in% FarmID_0_100$Farm_ID)


ggplot(eff_Model41_0_100_plot, aes(x = Variable, y = Milk_per_Milk_Cow))+
  geom_point(color = "#0066FF")+
  guides(colour=FALSE)+
  facet_grid(.~Variable_type, scale = "free_x")+
  xlab("Variates Value")+
  ylab("Production (Milk per Milk Cow) Efficiency")+
  ggtitle("Production Efficiency Score versus Variates (0 - 100 Cows)")
@
\caption{Production Efficiency Score versus Variates (0 - 100 Cows)}
\end{figure}

\begin{figure}[H]
<<03312016_4, fig=TRUE, height= 5, width=7, warning= F, message=FALSE, echo=FALSE>>=

eff_Model41_100_275_plot = 
eff_Model41_plot%>%
  filter(Farm_ID %in% FarmID_100_275$Farm_ID)


ggplot(eff_Model41_100_275_plot, aes(x = Variable, y = Milk_per_Milk_Cow))+
  geom_point(color = "#99CC00")+
  guides(colour=FALSE)+
  facet_grid(.~Variable_type, scale = "free_x")+
  xlab("Variates Value")+
  ylab("Production (Milk per Milk Cow) Efficiency")+
  ggtitle("Production Efficiency Score versus Variates (100-275 Cows)")
@
\caption{Production Efficiency Score versus Variates (100-275 Cows)}
\end{figure}


\subsection{Two-Step DEA}
In this section we run two step DEA on the Annual Data.
\textbf{Step 1}: For the whole data, we estimate efficiency score using DEA.
\textbf{Step 2}: We run a tobit regression of efficiency score on four variates (daily IOFC Surplus Group, Crop Cost, Purchased Feed and Corn Silage). The results are as follows.
<<echo = FALSE>>=

Annual_eff = Annual_data
for(a in Outputs){
  Annual_eff%<>%
    bind_cols(., dea(data.frame(Annual_data[Inputs]), data.frame(Annual_data[a]))["eff"])
}

colnames(Annual_eff)[61:65] = lapply(Outputs, function(x) paste("eff_", x, sep = ""))


tobit_1 = censReg(Annual_eff$eff_Milk_per_Milk_Cow~
                  Annual_eff$Pur_Feed_Calc+
                  #Annual_eff$Feed_Cost__All_Animals__Annual+
                  Annual_eff$Corn_silage+
                  Annual_eff$Fecal_Starch+
                  #Annual_eff$pH+
                  Annual_eff$MUN,
                  #Annual_eff$Starch___DM,
                  left = 0, right = 1)
summary(tobit_1)
@

The coefficients of the tobit regression are:
<<echo = FALSE>>=
coef(tobit_1)
@

The marginal effects $\frac{\partial \mathbbm{E}(Y|X)}{\partial x_j}$ are
<<echo = FALSE>>=
margEff(tobit_1)
@

\end{document}